# fly.toml app configuration file generated for masternode-app on 2023-07-10T11:06:36+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "masternode-app"
primary_region = "hkg"


[build]
 dockerfile = "Dockerfile"


[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
