name: MasterNode Deploy
on:
  push:
    branches:
      - dev/satish
jobs:
  deploy:
    name: Deploy MasterNode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}